# Generated by Django 4.1.3 on 2022-12-27 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SuperAdmin', '0001_initial'),
        ('StaffManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffManager.teamlead_register')),
            ],
        ),
        migrations.CreateModel(
            name='TaskToEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teamleader.employee_register')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StaffManager.teamlead_register')),
                ('lead_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SuperAdmin.leadcreate')),
            ],
        ),
    ]
